
  # Namespace where the deployment will be created                  
namespace: my-project1

# Name of the application
fullname: nginx-proxy

# Number of replicas
replicaCount: 2

# History limit of revisions
revisionHistoryLimit: 10

# History limit of revisions
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 1
    maxSurge: 1
    
# Labels for the deployment and pods    
labels:
  app: nginx-proxy
  environment: production
  
 # Selector and Labels for the deployment and pods
selector:
  matchLabels:
    app: nginx-proxy
    environment: production
    
# Template labels for the deployment and pods
template:
  labels:
    app: nginx-proxy
    environment: production

 # Image pull secrets for accessing private registries
imagePullSecrets:
  - name: registry-dockerhub   

# Image configuration
image:
  repository: docker.io/paphat82/nginx-reverse-proxy
  tag: latest
  pullPolicy: IfNotPresent
  
# Container configuration
containers:
  containerPort: 80
  env:
    - name: TZ
      value: "Asia/Bangkok"
  resources:
    limits:
      memory: 3Gi
      cpu: '1'
    requests:
      memory: 50Mi
      cpu: 50m
      
 # ConfigMap configuration
configMap:
  enabled: true
  name: nginx-config
  data:
    nginx.conf: |
      events {
        worker_connections 1024;
      }

      http {
        server {
          listen 80;
          location / {
            proxy_pass http://nodejs-app:8080; 
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
          }
        }
      }

volumes: {}
nodeSelector: {}
affinity: {}
tolerations: []

#service
service:
  enabled: true
  type: ClusterIP
  port: 80
  labels:
    app: nginx-proxy
  containerPort: 80
  
serviceAccount:
  create: false
  use_existing: false
  name: ""
  
# HPA configuration
hpa:
  minReplicas: 2
  maxReplicas: 5
  metrics:
    cpu:
      averageUtilization: 50

