apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: {{ .Values.fullname }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.app }}
    spec:
      imagePullSecrets:
        {{- if .Values.imagePullSecrets }}
        {{- range .Values.imagePullSecrets }}
      - name: {{ .name | quote }}
        {{- end }}
        {{- end }}
        
      containers:
        - name: {{ .Values.fullname }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          ports:
            - containerPort: {{ .Values.containers.containerPort | default 80 }}
          env:
            {{- toYaml .Values.containers.env | nindent 12 }}
          resources:
            {{- toYaml .Values.containers.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: ""  # กำหนดหากต้องการ mount โฟลเดอร์ภายใน
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.name }}
